  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      #- RUN_OPTS=run options here #optional
    volumes:
      - /media/pi/External/appdata/jackett:/config
      - /media/pi/External/Downloads/.torrents:/downloads
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jackett.rule=Host(`jackett.feignman.duckdns.org`)"
      - "traefik.http.routers.jackett.entrypoints=websecure"
      - "traefik.http.routers.jackett.middlewares=auth@file"
    ports:
      - 9117:9117
    restart: unless-stopped
