  grafana:
    container_name: grafana
    image: grafana/grafana:6.3.6
    restart: unless-stopped
    user: "0"
    ports:
      - 3000:3000
    env_file:
      - ./services/grafana/grafana.env
    volumes:
      - /media/pi/External/appdata/grafana/data:/var/lib/grafana
      - /media/pi/External/appdata/grafana/log:/var/log/grafana
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana.feignman.duckdns.org`)"
      - "traefik.http.routers.grafana.entrypoints=websecure"
