  traefik:
    image: traefik:chevrotin
    container_name: traefik
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    environment:
      - TZ=Europe/Paris
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./services/traefik/traefik.toml:/etc/traefik/traefik.toml
      - ./letsencrypt/acme.json:/acme.json
    restart: unless-stopped
