  telegraf:
     container_name: telegraf
     image: telegraf:1.24.4
     restart: unless-stopped
     # Added for latest telegraf: https://www.influxdata.com/blog/docker-run-telegraf-as-non-root/
     user: telegraf:133
     privileged: true
     environment:
       HOST_PROC: /rootfs/proc
       HOST_SYS: /rootfs/sys
       HOST_ETC: /rootfs/etc
     volumes:
       - ./services/telegraf/zimaboard.conf:/etc/telegraf/telegraf.conf:ro
       - /var/run/docker.sock:/var/run/docker.sock:ro
       - /sys:/rootfs/sys:ro
       - /proc:/rootfs/proc:ro
       - /etc:/rootfs/etc:ro
