  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      #- UMASK_SET=022 #optional
    volumes:
      - /media/pi/External:/data
      - /media/pi/External/appdata/plex/config:/config
      - /media/pi/External/appdata/plex/transcode:/transcode
    restart: unless-stopped
