  plex:
    image: ghcr.io/linuxserver/plex:1.20.4.3517-ab5e1197c-ls124
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      #- UMASK_SET=022 #optional
    volumes:
      - /mnt/internalssd:/data
      - /mnt/internalssd/appdata/plex/config:/config
      - /mnt/internalssd/appdata/plex/transcode:/transcode
    restart: unless-stopped
