  vaultwarden:
    image: vaultwarden/server:1.27.0-alpine
    container_name: vaultwarden
    volumes:
      - /var/lib/iotstack/vaultwarden:/data/
    ports:
      - 8090:80
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vaultwarden.rule=Host(`vaultwarden.feignman.duckdns.org`)"
      - "traefik.http.routers.vaultwarden.entrypoints=websecure"
