# File Provider for access to deluge
# https://stackoverflow.com/questions/46245684/how-to-get-traefik-to-redirect-to-specific-non-docker-port-from-inside-docker

[http.routers]
    [http.routers.deluge]
        rule = "Host(`deluge.feignman.duckdns.org`)"
        entrypoints = ["websecure"]
        service = "deluge"
        [http.routers.deluge.tls]
            certResolver = "leresolver"
    [http.routers.hassio]
        rule = "Host(`hassio.feignman.duckdns.org`)"
        entrypoints = ["websecure"]
        service = "hassio"
        [http.routers.hassio.tls]
            certResolver = "leresolver"

[http.services]
    [http.services.deluge.loadBalancer]
        [[http.services.deluge.loadBalancer.servers]]
        # IP of iotstack-default network gateway, since deluge is on host network
            url = "http://172.18.0.1:8112"

    [http.services.hassio.loadBalancer]
        [[http.services.hassio.loadBalancer.servers]]
            url = "http://192.168.1.66:8123"

[http.middlewares]
    [http.middlewares.auth.basicauth]
        users = [
            "ishan:$2y$05$sRRTRD4ZGOOOsrAZKv60/es/s0AwgYWGvlLxL2amkN5yBqbMsaiSm",
            "aurelia:$2y$05$nt/XLqyGeieIp1oNQ7110.WyGyupcDrn9soC5U9s66zM3Xbiojjtq"
        ]
    #   removeheader = true