  portainer:
    container_name: portainer
    image: portainer/portainer:1.24.2
    restart: unless-stopped
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/iotstack/portainer/data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.feignman.duckdns.org`)"
      - "traefik.http.routers.portainer.entrypoints=websecure"
