  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - UMASK_SET=000 #optional
    volumes:
      - /mnt/internalssd/appdata/radarr/config:/config
      - /mnt/internalssd/Movies:/movies
      - /mnt/internalssd/Downloads:/downloads
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.rule=Host(`radarr.feignman.duckdns.org`)"
      - "traefik.http.routers.radarr.entrypoints=websecure"
      - "traefik.http.routers.radarr.middlewares=auth@file"
    ports:
      - 7878:7878
    restart: unless-stopped
  