  influxdb:
    container_name: influxdb
    image: "influxdb:latest"
    restart: unless-stopped
    ports:
      - 8086:8086
      - 8083:8083
      - 2003:2003
    env_file:
      - ./services/influxdb/influxdb.env
    volumes:
      - /media/pi/External/appdata/influxdb/data:/var/lib/influxdb
      - /media/pi/External/appdata/influxdb/db:/var/lib/influxdb/backup
