  sonarr:
    image: linuxserver/sonarr:4.0.9
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - UMASK_SET=022 #optional
    volumes:
      - /var/lib/iotstack/sonarr/config:/config
      - /mnt/externalraid/Series:/series
      - /mnt/externalraid/Downloads:/downloads
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.feignman.duckdns.org`)"                 
      - "traefik.http.routers.sonarr.entrypoints=websecure"                                    
      - "traefik.http.routers.sonarr.middlewares=auth@file"
    ports:
      - 8989:8989
    restart: unless-stopped
