  mariadb:
    image: linuxserver/mariadb
    container_name: mariadb
    env_file:
      - ./services/mariadb/mariadb.env
    volumes:
      - /mnt/externalraid/appdata/mariadb/config:/config
    ports:
      - 3306:3306
    restart: unless-stopped

