  deluge:
    image: linuxserver/deluge
    container_name: deluge
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      #- UMASK_SET=022 #optional
      #- DELUGE_LOGLEVEL=error #optional
    volumes:
      - /var/lib/iotstack/deluge/config:/config
      - /mnt/externalraid/Downloads:/downloads
    restart: unless-stopped
