  deluge:
    image: linuxserver/deluge
    container_name: deluge
    network_mode: host
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Paris
      #- UMASK_SET=022 #optional
      #- DELUGE_LOGLEVEL=error #optional
    volumes:
      - /media/pi/External/appdata/deluge/config:/config
      - /media/pi/External/Downloads:/downloads      
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.deluge.rule=Host(`deluge.feignman.duckdns.org`)"
      - "traefik.http.routers.deluge.entrypoints=websecure"
      - traefik.http.services.deluge.loadbalancer.server.port=8112
    restart: unless-stopped
