  nzbget:
    image: ghcr.io/linuxserver/nzbget
    container_name: nzbget
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - UMASK_SET=022 #optional
    volumes:
      - <path_to_volumes>/nzbget/config:/config
      - <path_to_nas>/Downloads:/downloads
    ports:
      - 6789:6789
    restart: unless-stopped